apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portal

resources:
  - deployment.yaml
  - ingressroute.yaml

images:
  - name: backup-manager
    newName: backup-manager
    newTag: latest
