apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-fs-data-ec
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  # Match your cluster + FS + pool names
  clusterID: rook-ceph
  fsName: ceph-fs
  pool: ceph-fs-data-ec
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
