operatorNamespace: rook-ceph

cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
    allowUnsupported: false

  dataDirHostPath: /var/lib/rook

  mon:
    count: 3
    allowMultiplePerNode: false
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - anakin.local
                    - obiwan.local
                    - rey.local

  dashboard:
    enabled: true
    ssl: false

  crashCollector:
    disable: true

  mgr:
    modules:
      - name: balancer
        enabled: true

  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
      storeType: "bluestore"
      deviceClass: "nvme"
    nodes:
      - name: anakin.local
        devices:
          - name: /dev/nvme0n1p3
      - name: obiwan.local
        devices:
          - name: /dev/nvme0n1p3
      - name: rey.local
        devices:
          - name: /dev/nvme0n1p3

# Pools
cephBlockPools:
  - name: ceph-blockpool
    spec:
      replicated:
        size: 3
      enableRBDStats: true
    storageClass:
      enabled: true
      name: ceph-block
      isDefault: true
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        imageFeatures: layering,exclusive-lock,object-map,fast-diff
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
        csi.storage.k8s.io/fstype: ext4

# CephFS with both replicated + EC pool
cephFileSystems:
  - name: ec-fs
    spec:
      preservePoolsOnDelete: true

      metadataPool:
        name: ec-fs-metadata
        replicated:
          size: 3
        parameters:
          pg_autoscale_mode: "on"

      # Replicated pool for default data
      dataPools:
        - name: ec-fs-data-repl
          replicated:
            size: 3
          parameters:
            pg_autoscale_mode: "on"

        # EC pool for bulk data
        - name: ec-fs-data-ec
          failureDomain: host
          erasureCoded:
            dataChunks: 2
            codingChunks: 1
          parameters:
            pg_autoscale_mode: "on"
            allow_ec_overwrites: "true"
            bulk: "true"

      metadataServer:
        activeCount: 1
        activeStandby: true
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - anakin.local
                        - obiwan.local
                        - rey.local

    storageClass:
      enabled: true
      name: ceph-filesystem
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        clusterID: rook-ceph
        fsName: ec-fs
        pool: ec-fs-data-repl
        csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
        csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
        csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
        csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
        csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph

csi:
  enableCephfsDriver: true
  enableRbdDriver: true
  enableRBDSnapshotter: true
  enableNFSDriver: true

toolbox:
  enabled: true
