crds:
  enabled: true

csi:
  enableRbdDriver: true
  enableCephfsDriver: false

monitoring:
  enabled: false

toolbox:
  enabled: false

dashboard:
  enabled: true
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.248

ingress:
  enabled: false

enableDiscoveryDaemon: false

# Per-component resource overrides
mon:
  count: 3
  allowMultiplePerNode: false
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 768Mi

mgr:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

osd:
  resources:
    limits:
      cpu: 750m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi