# tvh-values.yml
image:
  # Prefer lscr.io, which is the official multi-arch endpoint
  repository: lscr.io/linuxserver/tvheadend
  # tag: latest            # omit to follow chart default (multi-arch)
  pullPolicy: IfNotPresent

env:
  TZ: America/New_York
  PUID: "1000"
  PGID: "1000"

# Let TVH see LAN broadcasts (HDHomeRun autodiscovery & DLNA)
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

service:
  main:
    ports:
      http:
        port: 9981        # TVH web UI / XMLTV export (HTTP)
      htsp:
        enabled: true     # enable HTSP (Kodi/clients)
        protocol: TCP
        port: 9982

ingress:
  main:
    enabled: false        # We'll use Traefik IngressRoute CRDs instead

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 5Gi
    storageClass: ceph-fs-data-ec   # <--- set if you want a specific SC
    accessMode: ReadWriteOnce    # storageClass: rook-ceph-cephfs   # uncomment to pin SC
  recordings:
    enabled: true
    mountPath: /recordings
    size: 5Gi
    storageClass: ceph-fs-data-ec   # <--- set if you want a specific SC
    accessMode: ReadWriteOnce    # storageClass: rook-ceph-cephfs

# keep fsGroup and allow root at start for s6
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 0
  runAsGroup: 0
