# image from lscr.io is good (multi-arch). Keep that change.
image:
  repository: lscr.io/linuxserver/tvheadend
  pullPolicy: IfNotPresent
  # tag:  # omit to let it select the right arch

env:
  TZ: America/New_York
  PUID: "1000"
  PGID: "1000"

# host networking for HDHomeRun discovery is fine to keep
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet

service:
  main:
    ports:
      http:
        port: 9981        # TVH web UI / XMLTV export (HTTP)
      htsp:
        enabled: true     # enable HTSP (Kodi/clients)
        protocol: TCP
        port: 9982

ingress:
  main:
    enabled: false        # We'll use Traefik IngressRoute CRDs instead

persistence:
  config:
    enabled: true
    mountPath: /config
    size: 5Gi
    storageClass: ceph-fs-data-ec   # <--- set if you want a specific SC
    accessMode: ReadWriteMany    # storageClass: rook-ceph-cephfs   # uncomment to pin SC
  recordings:
    enabled: true
    mountPath: /recordings
    size: 5Gi
    storageClass: ceph-fs-data-ec   # <--- set if you want a specific SC
    accessMode: ReadWriteMany    # storageClass: rook-ceph-cephfs

# <-- IMPORTANT: let s6 start as root and keep FS executable/writable
securityContext:
  runAsUser: 0
  runAsGroup: 0
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  capabilities:
    add: ["CHOWN","FOWNER","SETGID","SETUID","DAC_OVERRIDE"]

# keep CephFS write perms for mounted volumes
podSecurityContext:
  fsGroup: 1000

probes:
  startup:
    enabled: true
    spec:
      httpGet:
        path: /
        port: 9981
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 30
  liveness:
    enabled: true
    spec:
      httpGet:
        path: /
        port: 9981
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 10
  readiness:
    enabled: true
    spec:
      httpGet:
        path: /
        port: 9981
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 10