server:
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 50Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

grafana:
  nodeSelector:
    kubernetes.io/arch: "arm64"
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.246"
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi

prometheusOperator:
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.245"
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/arch: "arm64"
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus

nodeExporter:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Global storage defaults
storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: rook-ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/arch: "arm64"
    retention: 15d
    retentionSize: "10GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi