server:
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block-storage-ec"
    size: 50Gi
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

grafana:
  nodeSelector:
    kubernetes.io/arch: "arm64"
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.246"
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus
  persistence:
    enabled: true
    storageClass: "rook-ceph-block-storage-ec"
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

prometheusOperator:
  nodeSelector:
    kubernetes.io/arch: "arm64"
  tls:
    enabled: false
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.244"
    port: 8080
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  createCustomResource: false
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
  crds:
    enabled: true
    create: false

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/arch: "arm64"
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.245"
    annotations:
      metallb.universe.tf/allow-shared-ip: prometheus

nodeExporter:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

storageSpec:
  volumeClaimTemplate:
    spec:
      storageClassName: rook-ceph-block-storage-ec
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Gi

prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/arch: "arm64"
    retention: 15d
    retentionSize: "10GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block-storage-ec
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi