# Common settings
commonNodeSelector: &commonNodeSelector
  kubernetes.io/arch: "arm64"

commonStorageClass: &commonStorageClass
  storageClassName: rook-ceph-block
  accessModes: ["ReadWriteOnce"]

commonLoadBalancerAnnotation: &commonLoadBalancerAnnotation
  metallb.universe.tf/allow-shared-ip: prometheus

# Grafana configuration
grafana:
  nodeSelector: *commonNodeSelector
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.246"
    annotations: *commonLoadBalancerAnnotation
  persistence:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Prometheus Operator configuration
prometheusOperator:
  nodeSelector: *commonNodeSelector
  tls:
    enabled: false
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.244"
    port: 8080
    annotations: *commonLoadBalancerAnnotation
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  createCustomResource: false
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
  crds:
    enabled: true
    create: false

# Alertmanager configuration
alertmanager:
  alertmanagerSpec:
    nodeSelector: *commonNodeSelector
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.245"
    annotations: *commonLoadBalancerAnnotation
  persistentVolume:
    enabled: true
    storageClass: "rook-ceph-block"
    size: 10Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Node Exporter configuration
nodeExporter:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

# Kube State Metrics configuration
kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Prometheus configuration
prometheus:
  prometheusSpec:
    nodeSelector: *commonNodeSelector
    retention: 15d
    retentionSize: "10GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          <<: *commonStorageClass
          resources:
            requests:
              storage: 50Gi
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.1.251"
      annotations: *commonLoadBalancerAnnotation