server:
  persistentVolume:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.1.245"
    annotations: {}
    labels: {}
    externalPort: 80
    port: 80
    targetPort: 9090

# Reduce resource usage for components
alertmanager:
  persistentVolume:
    enabled: false
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeExporter:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

kubeStateMetrics:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Disable components not needed
pushgateway:
  enabled: false
  persistentVolume:
    enabled: false