ollama:
  enabled: false

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 250Gi
  storageClass: "ceph-block-data"
  accessMode: ReadWriteMany

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 80

# Traefik ingress
ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: seadogger-homelab.local
      paths:
        - path: /openwebui
          pathType: Prefix
  tls:
    - secretName: openwebui-local-tls
      hosts:
        - seadogger-homelab.local