ollama:
  enabled: false

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 250Gi
  storageClass: "ceph-block-data"
  # RBD is RWO; if you truly need RWX, use a CephFS storageClass instead.
  accessModes:
    - ReadWriteOnce

service:
  type: ClusterIP
  port: 80
  # chart exposes containerPort as a named port "http" (8080)
  # omit targetPort or set to "http" to follow the container's 8080
  targetPort: http
  containerPort: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: seadogger-homelab.local
      paths:
        - path: /openwebui
          pathType: Prefix
  tls:
    - secretName: openwebui-local-tls
      hosts:
        - seadogger-homelab.local
