ollama:
  enabled: false

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 250Gi
  storageClass: "ceph-block-data"
  accessMode: ReadWriteMany

# Service configuration
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.243
  port: 80
  targetPort: 80
