ollama:
  enabled: false

pipelines:
  enabled: false

persistence:
  enabled: true
  size: 250Gi
  storageClass: "ceph-block-data"
  accessMode: ReadWriteMany

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: http  

ingress:
  enabled: false

