ollama:
  enabled: false

pipelines:
  enabled: false

persistentVolumeClaim:
  enabled: true
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: "rook-cephfs"

persistence:
  enabled: true

# Service configuration
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.243
  port: 80
  targetPort: 80
