apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-dashboard-certificate
  namespace: argocd
spec:
  secretName: argocd-local-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  subject:
    organizations:
      - SeaDogger Homelab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - argocd.local
  issuerRef:
    name: internal-local-issuer
    kind: ClusterIssuer
