apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.4
    helm:
      values: |
        installCRDs: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: false
        webhook:
          enabled: true
          securePort: 443
          hostNetwork: false
          serviceType: ClusterIP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
