apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-ro
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""          # bind to static PV
  volumeName: jellyfin-nextcloud-media-ro
