---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmltv-proxy-script
  namespace: jellyfin
data:
  proxy.py: |
    #!/usr/bin/env python3
    """
    Simple HTTP proxy that fetches XMLTV from HDHomeRun API
    and serves it uncompressed (no gzip) for Jellyfin compatibility.
    """
    from http.server import HTTPServer, BaseHTTPRequestHandler
    import urllib.request
    import sys
    import os

    # HDHomeRun API configuration from environment variables
    EMAIL = os.environ.get('HDHOMERUN_EMAIL', '')
    DEVICE_IDS = os.environ.get('HDHOMERUN_DEVICE_IDS', '')

    if not EMAIL or not DEVICE_IDS:
        print("ERROR: HDHOMERUN_EMAIL and HDHOMERUN_DEVICE_IDS environment variables must be set", file=sys.stderr, flush=True)
        sys.exit(1)

    API_URL = f"https://api.hdhomerun.com/api/xmltv?Email={EMAIL}&DeviceIDs={DEVICE_IDS}"

    class XMLTVProxyHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            if self.path == "/xmltv.xml" or self.path == "/":
                try:
                    # Fetch from HDHomeRun API with explicit no-gzip encoding
                    req = urllib.request.Request(API_URL)
                    req.add_header('Accept-Encoding', 'identity')

                    with urllib.request.urlopen(req, timeout=30) as resp:
                        xml_data = resp.read()

                    # Send response (explicitly uncompressed)
                    self.send_response(200)
                    self.send_header('Content-Type', 'application/xml; charset=utf-8')
                    self.send_header('Content-Length', str(len(xml_data)))
                    # Explicitly prevent compression
                    self.send_header('Content-Encoding', 'identity')
                    self.end_headers()
                    self.wfile.write(xml_data)

                    print(f"Successfully served {len(xml_data)} bytes of XMLTV data", flush=True)

                except Exception as e:
                    print(f"Error fetching XMLTV: {e}", file=sys.stderr, flush=True)
                    self.send_error(500, f"Failed to fetch XMLTV: {e}")
            else:
                self.send_error(404, "Not Found")

        def log_message(self, format, *args):
            # Print logs to stdout with flush for immediate visibility
            print(f"{self.address_string()} - {format % args}", flush=True)

    if __name__ == "__main__":
        PORT = 8080
        server = HTTPServer(('0.0.0.0', PORT), XMLTVProxyHandler)
        print(f"XMLTV Proxy server running on port {PORT}", flush=True)
        print(f"Proxying: {API_URL}", flush=True)
        server.serve_forever()

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmltv-proxy
  namespace: jellyfin
  labels:
    app: xmltv-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmltv-proxy
  template:
    metadata:
      labels:
        app: xmltv-proxy
    spec:
      containers:
      - name: proxy
        image: python:3.11-alpine
        command: ["python3", "/app/proxy.py"]
        ports:
        - containerPort: 8080
        env:
        - name: HDHOMERUN_EMAIL
          valueFrom:
            secretKeyRef:
              name: hdhomerun-credentials
              key: email
        - name: HDHOMERUN_DEVICE_IDS
          valueFrom:
            secretKeyRef:
              name: hdhomerun-credentials
              key: device-ids
        volumeMounts:
        - name: script
          mountPath: /app
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      volumes:
      - name: script
        configMap:
          name: xmltv-proxy-script
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: xmltv-proxy
  namespace: jellyfin
spec:
  selector:
    app: xmltv-proxy
  ports:
  - port: 80
    targetPort: 8080
