apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-memory-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-data
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basic-memory-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-data
  resources:
    requests:
      storage: 2Gi
