apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mealie-certificate
spec:
  secretName: mealie-local-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - SeaDogger Homelab
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - mealie.seadogger-homelab
  issuerRef:
    name: internal-local-issuer
    kind: ClusterIssuer
