apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - certificate.yaml
  - ingressroutes.yaml

configMapGenerator:
  - name: mealie-custom-prompts
    files:
      - prompts/recipes/parse-recipe-ingredients.txt
      - prompts/recipes/parse-recipe-image.txt
      - prompts/recipes/parse-recipe-video.txt
      - prompts/recipes/scrape-recipe.txt
