apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-access-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-access-gateway
  template:
    metadata:
      labels:
        app: bedrock-access-gateway
    spec:
      imagePullSecrets:
        - name: aws-access-key-id
        - name: aws-secret-access-key
      containers:
        - name: bedrock-access-gateway
          image: dayaengineering/bedrock-access-gateway:20241211115329
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws-secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-west-2"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DEBUG
              value: "true"
      nodeSelector:
        kubernetes.io/arch: arm64

---
apiVersion: v1
kind: Service
metadata:
  name: bedrock-access-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: bedrock-access-gateway
  ports:
    - protocol: TCP
      port: 6880
      targetPort: 80
  loadBalancerIP: 192.168.1.242