apiVersion: v1
kind: Service
metadata:
  name: bedrock-access-gateway-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bedrock-access-gateway
  ports:
    - protocol: TCP
      port: 6880
      targetPort: 80
  loadBalancerIP: 192.168.1.242