---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: n8n-backup-schedule
  namespace: n8n
spec:
  # Backend configuration for S3 Deep Archive
  backend:
    s3:
      endpoint: https://s3.amazonaws.com
      bucket: seadogger-homelab-backup
      accessKeyIDSecretRef:
        name: k8up-s3-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
    repoPasswordSecretRef:
      name: k8up-s3-credentials
      key: RESTIC_PASSWORD

  # Daily backup at 3 AM (after Nextcloud)
  backup:
    # Run daily at 3:00 AM Pacific Time
    schedule: "0 3 * * *"
    # Keep last successful backup job for debugging
    keepJobs: 3
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    # Backup all PVCs in the namespace
    podSecurityContext:
      runAsUser: 0
      fsGroup: 0

  # Weekly integrity check on Sundays at 2 AM
  check:
    schedule: "0 2 * * 0"
    keepJobs: 3
    promURL: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090

  # Weekly prune to apply retention policy on Sundays at 4 AM
  prune:
    schedule: "0 4 * * 0"
    keepJobs: 3
    retention:
      # Keep 14 daily backups (2 weeks)
      keepDaily: 14
      # Keep 8 weekly backups (2 months)
      keepWeekly: 8
      # Keep 6 monthly backups
      keepMonthly: 6
      # Keep last 20 backups
      keepLast: 20
