---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: nextcloud-backup-schedule
  namespace: nextcloud
spec:
  # Backend configuration for S3 Deep Archive
  backend:
    s3:
      endpoint: https://s3.amazonaws.com
      bucket: seadogger-homelab-backup
      accessKeyIDSecretRef:
        name: k8up-s3-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
    repoPasswordSecretRef:
      name: k8up-s3-credentials
      key: RESTIC_PASSWORD

  # Daily backup at 2 AM
  backup:
    # Run daily at 2:00 AM Pacific Time
    schedule: "0 2 * * *"
    # Keep last successful backup job for debugging
    keepJobs: 3
    # Fail if backup takes longer than 1 hour
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    # Backup all PVCs in the namespace
    podSecurityContext:
      runAsUser: 0
      fsGroup: 0

  # Weekly integrity check on Sundays at 1 AM
  check:
    schedule: "0 1 * * 0"
    keepJobs: 3
    promURL: http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090

  # Weekly prune to apply retention policy on Sundays at 3 AM
  prune:
    schedule: "0 3 * * 0"
    keepJobs: 3
    retention:
      # Keep 7 daily backups
      keepDaily: 7
      # Keep 4 weekly backups
      keepWeekly: 4
      # Keep 6 monthly backups
      keepMonthly: 6
      # Keep last 14 backups
      keepLast: 14
