---
- name: Add ArgoCD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: "https://argoproj.github.io/argo-helm"
    state: present
    kubeconfig: "{{ KUBECONFIG }}"

- name: Create ArgoCD namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ KUBECONFIG }}"

- name: Deploy ArgoCD with Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    state: present
    kubeconfig: "{{ KUBECONFIG }}"

- name: Expose ArgoCD as a LoadBalancer service
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ KUBECONFIG }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        type: LoadBalancer
        selector:
          app.kubernetes.io/name: argocd-server
        ports:
          - name: http
            port: 80
            protocol: TCP
            targetPort: 8080
          - name: https
            port: 443
            protocol: TCP
            targetPort: 8080
        loadBalancerIP: 192.168.1.247
