---
    # Step 1: Set KUBECONFIG globally
    - name: Set KUBECONFIG global
      ansible.builtin.set_fact:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        argocd_force_clean_install: "{{ argocd_force_clean_install | default(false) }}"

    # Clean install path
    - name: Delete ArgoCD namespace if it exists
      ansible.builtin.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd
      become: true
      when: argocd_force_clean_install | default(false)

    - name: Wait for namespace deletion
      ansible.builtin.pause:
        seconds: 30
      when: argocd_force_clean_install | default(false)

    # Common steps for both paths
    - name: Add ArgoCD Helm repository
      ansible.builtin.shell:
        cmd: helm repo add argo https://argoproj.github.io/argo-helm
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    - name: Update Helm repositories
      ansible.builtin.shell:
        cmd: helm repo update
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    # Download and modify values.yaml
    - name: Download ArgoCD values.yaml from Helm repository
      ansible.builtin.shell:
        cmd: helm show values argo/argo-cd > /tmp/argocd-values.yaml
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    - name: Enable insecure mode in ArgoCD values.yaml
      ansible.builtin.lineinfile:
        path: /tmp/argocd-values.yaml
        regexp: '^#?insecure:.*'
        line: 'insecure: true'
      become: true

    # Installation/Update step
    - name: Install or upgrade ArgoCD
      ansible.builtin.shell:
        cmd: >
          {% if argocd_force_clean_install | default(false) %}
          helm install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-values.yaml
          {% else %}
          helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-values.yaml
          {% endif %}
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    # Wait for pods
    - name: Wait for ArgoCD pods to be running
      ansible.builtin.shell:
        cmd: |
          while [[ $(kubectl get pods -n argocd -l app.kubernetes.io/name=argocd-server -o 'jsonpath={.items[?(@.status.phase!="Running")].metadata.name}' | wc -w) -gt 0 ]]; do
            echo "Waiting for ArgoCD pods to be running..."
            sleep 5
          done
      become: true