---
    # Step 1: Set KUBECONFIG globally
    - name: Set KUBECONFIG global
      ansible.builtin.set_fact:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    # Common steps for both paths
    - name: Add ArgoCD Helm repository
      ansible.builtin.shell:
        cmd: helm repo add argo https://argoproj.github.io/argo-helm
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    - name: Update Helm repositories
      ansible.builtin.shell:
        cmd: helm repo update
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    # Download and modify values.yaml
    - name: Download ArgoCD values.yaml from Helm repository
      ansible.builtin.shell:
        cmd: helm show values argo/argo-cd > /tmp/argocd-values.yaml
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    - name: Enable insecure mode in ArgoCD values.yaml
      ansible.builtin.lineinfile:
        path: /tmp/argocd-values.yaml
        regexp: '^#?insecure:.*'
        line: 'insecure: true'
      become: true

    # Installation/Update step
    - name: Install or upgrade ArgoCD
      ansible.builtin.shell:
        cmd: helm upgrade --install argocd argo/argo-cd --namespace argocd --create-namespace -f /tmp/argocd-values.yaml
      environment:
        KUBECONFIG: "{{ KUBECONFIG }}"
      become: true

    # Wait for pods
    - name: Wait for ArgoCD pods to be running
      ansible.builtin.k8s_info:
        api_version: v1
        kind: Pod
        namespace: argocd
        label_selectors:
          - "app.kubernetes.io/name=argocd-server"
        kubeconfig: "{{ KUBECONFIG }}"
      register: argocd_pods
      retries: 20
      delay: 5
      until: argocd_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length == (argocd_pods.resources | length)
