---
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: "Clean up Prometheus Hybrid Application"
  block:
    # Step 1: Delete the ArgoCD Application resource.
    - name: "Delete Prometheus ArgoCD Application"
      community.kubernetes.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        kind: Application
        api_version: argoproj.io/v1alpha1
        name: prometheus-stack
        namespace: argocd
        wait: yes
        timeout: 300
      ignore_errors: true

    # Step 2: Delete extra resources like LoadBalancers and NetworkPolicies
    - name: "Delete Prometheus extra resources"
      community.kubernetes.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: monitoring
      loop:
        - { kind: "Service", name: "prometheus-k8s-lb" }
        - { kind: "Service", name: "grafana-lb" }
        - { kind: "Service", name: "alertmanager-main-lb" }
        - { kind: "NetworkPolicy", name: "allow-prometheus-external" }
        - { kind: "NetworkPolicy", name: "allow-grafana-external" }
        - { kind: "NetworkPolicy", name: "allow-alertmanager-external" }
      ignore_errors: true

    # Step 3 (Conditional): Delete PVCs if requested.
    - name: "Delete Prometheus PVCs"
      community.kubernetes.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        kind: PersistentVolumeClaim
        namespace: monitoring
        label_selector: "app.kubernetes.io/instance=kube-prometheus-stack"
      when: prometheus_delete_pvc | default(false)
      ignore_errors: true

    # Step 4: Delete the namespace.
    - name: "Delete monitoring namespace"
      community.kubernetes.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        kind: Namespace
        name: monitoring
        wait: yes
        timeout: 600
      ignore_errors: true

    # Step 5: Delete the CRDs LAST. This is the most critical step.
    - name: "Delete Prometheus CRDs from the cluster"
      community.kubernetes.k8s:
        kubeconfig: "{{ KUBECONFIG }}"
        state: absent
        definition: "{{ lookup('url', item, split_lines=False) }}"
      loop:
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0alertmanagerCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0podmonitorCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0prometheusCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0prometheusruleCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0servicemonitorCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0thanosrulerCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0probeCustomResourceDefinition.yaml"
        - "https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.13/manifests/setup/0alertmanagerConfigCustomResourceDefinition.yaml"
      ignore_errors: true
