---
# Step 1: Set KUBECONFIG globally
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# Download static PV manifest for Jellyfin media
- name: Download static PV manifest for Jellyfin media
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/seadogger-tech/seadogger-homelab-pro/main/core/deployments/jellyfin/static-pv.yaml
    dest: /tmp/jellyfin-static-pv.yaml
    mode: '0644'

- name: Apply static PV for Jellyfin media
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    src: /tmp/jellyfin-static-pv.yaml

# Download read‑only PVC manifest for Jellyfin media
- name: Download read‑only PVC manifest for Jellyfin media
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/seadogger-tech/seadogger-homelab-pro/main/core/deployments/jellyfin/ro-pvc.yaml
    dest: /tmp/jellyfin-ro-pvc.yaml
    mode: '0644'

- name: Apply read‑only PVC for Jellyfin media
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    src: /tmp/jellyfin-ro-pvc.yaml

# Step 2: Create ArgoCD Jellyfin Application
- name: Create Jellyfin ArgoCD Application
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: jellyfin
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://k8s-at-home.com/charts/
          chart: jellyfin
          targetRevision: "*"
          helm:
                valueFiles:
                  - https://raw.githubusercontent.com/seadogger-tech/seadogger-homelab-pro/main/core/deployments/jellyfin/jellyfin-values.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: jellyfin
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

# Step 3: Wait for Jellyfin application to be healthy
- name: Wait for Jellyfin application to be healthy
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: jellyfin
    namespace: argocd
    kubeconfig: "{{ KUBECONFIG }}"
  register: jellyfin_status
  until: jellyfin_status.resources is defined and
         jellyfin_status.resources[0].status.health.status is defined and
         jellyfin_status.resources[0].status.health.status == "Healthy"
  retries: 30
  delay: 10

# Apply Jellyfin subPath mounts for Videos and Music
- name: Apply Jellyfin subPath mounts
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jellyfin
        namespace: jellyfin
      spec:
        template:
          spec:
            containers:
              - name: jellyfin
                volumeMounts:
                  - name: media
                    mountPath: /videos
                    subPath: data/HomeMedia/files/Videos
                    readOnly: true
                  - name: media
                    mountPath: /music
                    subPath: data/HomeMedia/files/Music
                    readOnly: true
            volumes:
              - name: media
                persistentVolumeClaim:
                  claimName: jellyfin-media-ro

# Step 4: Download Jellyfin IngressRoutes manifest from GitHub
- name: Download jellyfin IngressRoutes manifest from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/ingress/traefik-jellyfin-ingress.yml"
    dest: "/tmp/traefik-jellyfin-ingress.yml"
    mode: "0644"

# Step 5: Apply Jellyfin IngressRoutes (no Helm/Argo)
- name: Apply Jellyfin IngressRoutes (no Helm/Argo)
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    src: "/tmp/traefik-jellyfin-ingress.yml"
