---
# Step 1: Set KUBECONFIG globally
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Add MetalLB Helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
    state: present
    kubeconfig: "{{ KUBECONFIG }}"

- name: Create MetalLB namespace
  kubernetes.core.k8s:
    name: metallb-system
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ KUBECONFIG }}"

- name: Deploy MetalLB with Helm (atomic + wait; no hard sleeps)
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb-system
    state: present
    kubeconfig: "{{ KUBECONFIG }}"
    atomic: true
    wait: true
    wait_timeout: 600s

# --- Replace fixed sleep with CRD establishment checks ---
- name: Define required MetalLB CRDs
  ansible.builtin.set_fact:
    metallb_crds:
      - ipaddresspools.metallb.io
      - l2advertisements.metallb.io
      - bgppeers.metallb.io
      - bgpadvertisements.metallb.io

- name: Wait for MetalLB CRDs to be Established
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    kubeconfig: "{{ KUBECONFIG }}"
  loop: "{{ metallb_crds }}"
  register: crd_status
  until: >
    crd_status.resources | length > 0 and
    (
      crd_status.resources[0].status.conditions | default([]) |
      selectattr('type','equalto','Established') |
      selectattr('status','equalto','True') |
      list | length
    ) > 0
  retries: 60
  delay: 2
  loop_control:
    label: "{{ item }}"

# --- Apply your CRs (no bogus wait_condition) ---
- name: Apply MetalLB Custom Resources (IPAddressPools, L2Advertisements)
  kubernetes.core.k8s:
    src: "https://raw.githubusercontent.com/seadogger/seadogger-homelab/refs/heads/master/helm-deployments/metallb/metallb-values.yaml"
    state: present
    kubeconfig: "{{ KUBECONFIG }}"
    apply: true

# --- Lightweight validation that CRs are present ---
- name: Wait for at least one IPAddressPool to exist
  kubernetes.core.k8s_info:
    api_version: metallb.io/v1beta1
    kind: IPAddressPool
    kubeconfig: "{{ KUBECONFIG }}"
  register: pools
  until: pools.resources | length > 0
  retries: 30
  delay: 2

- name: Wait for at least one L2Advertisement to exist
  kubernetes.core.k8s_info:
    api_version: metallb.io/v1beta1
    kind: L2Advertisement
    kubeconfig: "{{ KUBECONFIG }}"
  register: l2ads
  until: l2ads.resources | length > 0
  retries: 30
  delay: 2
