- name: Create n8n namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: n8n

- name: Deploy ArgoCD Application for n8n
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: n8n
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://n8n-io.github.io/n8n-helm
          targetRevision: '*'  # Use latest version of the chart
          chart: n8n
          helm:
            valueFiles:
              - https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/helm-deployments/n8n/n8n-values.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: n8n
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
