- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tags: n8n

- name: Create n8n ArgoCD Application
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: n8n
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://community-charts.github.io/helm-charts
          chart: n8n
          targetRevision: "1.15.1"
          helm:
            valueFiles:
              - https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/deployments/n8n/n8n-values.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: n8n
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true
  tags: n8n

- name: Poll until n8n pods are ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ KUBECONFIG }}"
    kind: Pod
    namespace: n8n
    label_selectors:
      - "app.kubernetes.io/instance=n8n"
  register: n8n_pods
  until: n8n_pods is defined and n8n_pods.resources is defined and (n8n_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length) > 0
  retries: 30
  delay: 5
  delegate_to: "{{ inventory_hostname }}"
  tags: n8n


- name: Download n8n IngressRoutes manifest from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/ingress/traefik-n8n-ingress.yml"
    dest: "/tmp/traefik-n8n-ingress.yml"
    mode: "0644"

- name: Apply n8n IngressRoutes (no Helm/Argo)
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    src: "/tmp/traefik-n8n-ingress.yml"
