# Step 1: Set KUBECONFIG globally
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# Step 2: Expose n8n as a LoadBalancer service with MetalLB
- name: Expose n8n as a LoadBalancer service
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: n8n-service
        namespace: n8n
      spec:
        type: LoadBalancer
        selector:
          app.kubernetes.io/name: n8n
          app.kubernetes.io/instance: n8n
        ports:
          - port: 80
            targetPort: 5678
            protocol: TCP
        loadBalancerIP: 192.168.1.252
  become: true
