---
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    
- name: Pre-cook Namespaces
  kubernetes.core.k8s:
    name: "{{ item.name }}"
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ KUBECONFIG }}"
    definition:
      metadata:
        labels:
          argocd.argoproj.io/managed-by: argocd
  loop: "{{ precook_namespaces }}"
