---
# Step 1: Set KUBECONFIG globally  
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# Step 8: Create ArgoCD Nextcloud Application
- name: Create Nextcloud ArgoCD Application
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: nextcloud
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://nextcloud.github.io/helm/
          chart: nextcloud
          targetRevision: "7.0.2"
          helm:
            valueFiles:
              - https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/deployments/nextcloud/nextcloud-values.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: nextcloud
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

- name: Wait for Nextcloud pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ KUBECONFIG }}"
    kind: Pod
    namespace: nextcloud
  register: nextcloud_pods
  retries: 30
  delay: 10
  until: nextcloud_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
  changed_when: false

- name: Download Nextcloud IngressRoutes manifest from GitHub
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/ingress/traefik-nextcloud-ingress.yml"
    dest: "/tmp/traefik-nextcloud-ingress.yml"
    mode: "0644"

- name: Apply Nextcloud IngressRoutes (no Helm/Argo)
  kubernetes.core.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    src: "/tmp/traefik-nextcloud-ingress.yml"
