---
# Step 1: Set KUBECONFIG globally
- name: Set KUBECONFIG global
  ansible.builtin.set_fact:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# Step 2: Create ArgoCD Pihole Application
- name: Create Pihole ArgoCD Application
  ansible.builtin.k8s:
    kubeconfig: "{{ KUBECONFIG }}"
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: pihole
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: https://mojo2600.github.io/pihole-kubernetes/
          chart: pihole
          targetRevision: "*"
          helm:
            valueFiles:
              - https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/deployments/pihole/pihole-values.yaml
        destination:
          server: https://kubernetes.default.svc
          namespace: pihole
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
            - CreateNamespace=true

# Step 3: Wait for Pihole pods to be ready
- name: Wait for Pihole pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ KUBECONFIG }}"
    kind: Pod
    namespace: pihole
  register: pihole_pods
  retries: 30
  delay: 10
  until: pihole_pods is defined and 'resources' in pihole_pods and (pihole_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0)
