project: default
source:
  repoURL: https://mojo2600.github.io/pihole-kubernetes/
  targetRevision: 2.27.0
  helm:
    valueFiles:
      - >-
        https://raw.githubusercontent.com/seadogger/seadogger-homelab/master/helm-deployments/pihole/pihole-values.yaml
  chart: pihole
destination:
  server: https://kubernetes.default.svc
  namespace: pihole
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
  sources:
    - chart:
        repoURL: https://mojo2600.github.io/pihole-kubernetes/
        targetRevision: 2.27.0
    - repoURL: https://github.com/seadogger/seadogger-homelab
      targetRevision: HEAD 
      path: helm-deployments/pihole