service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http

replicaCount: 1

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  extraEnvVars:
#    WEBHOOK_URL: "https://n8n.seadogger-homelab"

    #. access to n8n will be routed to https.  this will only work this way when setting up the 
    #   localhost tunnel to perform the initial Oauth2 handshake
    N8N_SECURE_COOKIE: "false" 

ingress:
  enabled: false

# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n

