service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  extraEnvVars:
    WEBHOOK_URL: "https://n8n.seadogger-homelab"

ingress:
  enabled: false

# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n

