apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playit-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-data
  resources:
    requests:
      storage: 100Mi  # Small — just stores playit.toml config
