---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - storage.yaml
  - services.yaml
  - statefulset.yaml
  - backup-cronjob.yaml
  - backup-alerts.yaml
configMapGenerator:
  - name: nextcloud-db-scripts
    files:
      - init.sh
      - backup.sh
generatorOptions:
  disableNameSuffixHash: true
