---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db-headless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: nextcloud-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-db
spec:
  selector:
    app.kubernetes.io/name: nextcloud-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
