---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-data
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block-data
  resources:
    requests:
      storage: 10Gi
