# Docker image configuration
image:
  registry: index.docker.io
  repository: plexinc/pms-docker
  tag: "latest"
  pullPolicy: IfNotPresent
  architecture: arm64

# Service configuration
service:
  main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.244
    ports:
      http:
        port: 32400
        targetPort: 32400
        protocol: TCP

# Storage configuration
persistence:
  config:
    enabled: true
    storageClass: "ceph-block"
    size: 50Gi
    accessMode: ReadWriteOnce
  
  transcode:
    enabled: true
    medium: Memory
    size: 10Gi
    type: emptyDir

# Environment variables
env:
  - name: "HOSTNAME"
    value: "PlexServer"
  - name: "TZ"
    value: "America/New_York"
  - name: "PLEX_CLAIM"
    valueFrom:
      secretKeyRef:
        name: plex-claim-secret
        key: claim
  - name: "ADVERTISE_IP"
    value: "http://192.168.1.244:32400"

# Resource limits
resources:
  limits:
    cpu: 3000m
    memory: 6Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Pod configuration
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Service account configuration
serviceAccount:
  create: true
  automountServiceAccountToken: true
  name: "plex-plex-media-server"

# Health checks
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    port: 32400
    path: /identity
  readiness:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    port: 32400
    path: /identity

# Pod annotations
podAnnotations: {}

# Additional labels
labels: {}

# Node selection
nodeSelector: {}

# Pod affinity rules
affinity: {}

# Pod tolerations
tolerations: []

# Update strategy
strategy:
  type: RollingUpdate

# Security context for containers
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

# Init containers configuration
initContainers: []

# Additional volumes
extraVolumes: []

# Additional volume mounts
extraVolumeMounts: []

# Extra environment variables (deprecated - use env instead)
extraEnv: []