# Docker image configuration
image:
  registry: index.docker.io
  repository: plexinc/pms-docker
  tag: "latest"
  pullPolicy: IfNotPresent
  architecture: arm64

# Service configuration
service:
  main:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.244
    ports:
      http:
        port: 32400

# Storage configuration
pms:
  storageClassName: ceph-block
  configStorage: 50Gi

extraEnv:
  HOSTNAME: "PlexServer"
  TZ: "America/New_York"
  ADVERTISE_IP: "http://192.168.1.244:32400"
  PLEX_CLAIM:
    secretKeyRef:
      name: plex-claim-secret
      key: claim

resources:
  limits:
    cpu: 3000m
    memory: 6Gi
  requests:
    cpu: 1000m
    memory: 2Gi

serviceAccount:
  create: true
  automountServiceAccountToken: true