namespace:
  create: true
  name: longhorn-system

global:
  registry:
    url: "docker.io"
    prefix: "longhornio"
    architecture: arm64

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

service:
  ui:
    type: LoadBalancer
    nodePort: 31280
    loadBalancerIP: 192.168.1.248
    selector:
      app: longhorn-ui
    ports:
      port: 80 
      targetPort: 8000
      protocol: TCP
