# NFS Ganesha Server Configuration
replicaCount: 1

image:
  repository: gcr.io/k8s-staging-sig-storage/nfs-provisioner
  tag: v3.0.1
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: rook-ceph-filesystem-ec
  size: 6000Gi

service:
  type: LoadBalancer
  nfsPort: 2049
  mountdPort: 20048
  rpcbindPort: 111
  nfsNodePort: 32049
  mountdNodePort: 32048
  rpcbindNodePort: 32111
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.253"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  privileged: true
  fsGroup: 2000
  runAsUser: 2000
  capabilities:
    add:
      - DAC_READ_SEARCH
      - SYS_RESOURCE
      - SETPCAP
      - SYS_ADMIN

# NFS Export Configuration
nfsExports:
  - path: /export
    access: 192.168.1.0/24
    options: rw,sync,no_subtree_check,no_root_squash

# Storage provisioner configuration
storageClass:
  create: true
  name: nfs
  defaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  mountOptions:
    - vers=4.1
    - noatime
