# NFS Ganesha Server Configuration
replicaCount: 1

image:
  repository: gcr.io/k8s-staging-sig-storage/nfs-provisioner
  tag: v3.0.1
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClass: rook-ceph-filesystem-ec
  size: 6000Gi

service:
  type: LoadBalancer
  externalTrafficPolicy: Local
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.253"
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: TCP
      targetPort: 20048
    - name: rpcbind
      port: 111
      protocol: TCP
      targetPort: 111

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  privileged: true
  capabilities:
    add:
      - DAC_READ_SEARCH
      - SYS_RESOURCE
      - SETPCAP
      - SYS_ADMIN

# NFS Export Configuration
nfsExports:
  - path: /export
    access: "*"
    options: rw,no_root_squash,insecure,no_subtree_check

# Storage provisioner configuration
storageClass:
  create: true
  name: nfs
  defaultClass: false
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  mountOptions:
    - vers=4.1
    - noatime
