image:
  repository: nextcloud
  tag: 27.1.3-apache-arm64v8
  pullPolicy: IfNotPresent

nextcloud:
  host: nextcloud.local
  username: admin
  password: changeme  # Change this!
  update: 0
  configs:
    php.ini: |
      memory_limit=2048M
      upload_max_filesize=16G
      post_max_size=16G
      max_execution_time=3600
      max_input_time=3600

persistence:
  enabled: true
  existingClaim: ""
  annotations: {}
  storageClass: "rook-ceph-block-storage-ec"
  accessMode: ReadWriteMany
  size: 6Ti

redis:
  enabled: true
  architecture: standalone
  image:
    repository: arm64v8/redis
    tag: "7.2"
  auth:
    enabled: true
    password: "changeme"  # Change this!
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  master:
    persistence:
      enabled: true
      storageClass: "rook-ceph-block-storage-ec"
      size: 8Gi

ingress:
  enabled: false

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: 2
    memory: 4Gi

postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 15-debian-11
  global:
    postgresql:
      auth:
        username: nextcloud
        password: changeme  # Change this!
        database: nextcloud
      storageClass: "rook-ceph-block-storage-ec"  # Added this
  primary:
    persistence:
      enabled: true
      storageClass: "rook-ceph-block-storage-ec"
      size: 10Gi
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 1Gi
  persistence:  # Added this section
    enabled: true
    storageClass: "rook-ceph-block-storage-ec"
    size: 10Gi
  volumePermissions:  # Added this section
    enabled: true
  architecture: standalone  # Added this
  auth:  # Added this section
    enablePostgresUser: true
    postgresPassword: "changeme"  # Change this!
    username: nextcloud
    password: "changeme"  # Change this!
    database: nextcloud

podSecurityContext:
  enabled: true
  fsGroup: 33

containerSecurityContext:
  enabled: true
  runAsUser: 33
  runAsGroup: 33

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1