# nextcloud-values.yaml

# --- App image ---
image:
  repository: docker.io/library/nextcloud
  tag: 31.0.8-apache
  pullPolicy: IfNotPresent

# --- Core Nextcloud settings ---
nextcloud:
  host: nextcloud.kube.home
  # data directory inside the container; must match volumeMounts
  datadir: /var/www/html/data
  # admin credentials (use an external secret in prod; these only apply on first install)
  username: admin
  password: changeme
  # trusted domains
  trustedDomains:
    - nextcloud.kube.home

# Optional extra environment (uncomment if you need them explicitly)
# extraEnv:
#   - name: PHP_MEMORY_LIMIT
#     value: "512M"

# --- Probes (sane defaults for Apache image) ---
livenessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  path: /status.php
  headers:
    - name: Host
      value: nextcloud.kube.home

readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  path: /status.php
  headers:
    - name: Host
      value: nextcloud.kube.home

# --- Security context (www-data:33) ---
podSecurityContext:
  fsGroup: 33

securityContext:
  runAsUser: 33
  runAsGroup: 33
  runAsNonRoot: true

# --- Service ---
service:
  type: ClusterIP
  port: 8080
  targetPort: 80

# --- Ingress ---
ingress:
  enabled: true
  className: nginx
  annotations: {}
  tls: []
  hosts:
    - host: nextcloud.kube.home
      paths:
        - path: /
          pathType: Prefix

# --- Persistence for Nextcloud (RWX via CephFS) ---
persistence:
  enabled: true
  # If you already have a bound PVC and want to reuse it, set existingClaim: nextcloud-nextcloud
  # existingClaim: nextcloud-nextcloud
  storageClass: ceph-fs-data-ec
  accessMode: ReadWriteMany
  size: 6000Gi
  # subPaths created by the chart (html, data, config, apps, tmp, themes, etc.)

# =====================================================
# DATABASE
# =====================================================

# Disable SQLite/internal DB to avoid conflict with MariaDB
internalDatabase:
  enabled: false

# Use bundled Bitnami MariaDB subchart (RWO via Ceph RBD)
mariadb:
  enabled: true
  image:
    repository: docker.io/bitnami/mariadb
    tag: 11.4-debian-12     # valid tag; avoids the -r0 NotFound
    pullPolicy: IfNotPresent
  architecture: standalone
  auth:
    database: nextcloud
    username: nextcloud
    password: changeme      # set a strong one or source from existing secret (see below)
    # Existing secret support (uncomment to use your existing 'nextcloud-db' secret)
    # existingSecret: nextcloud-db
    # secretKeys:
    #   userPasswordKey: db-password
    #   rootPasswordKey: mariadb-root-password
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block-data
      accessModes:
        - ReadWriteOnce
      size: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 768Mi

# If you want to connect Nextcloud to an external DB instead of the subchart,
# disable mariadb.enabled and set externalDatabase.* accordingly:
externalDatabase:
  enabled: false
  type: mysql
  host: nextcloud-mariadb
  database: nextcloud
  user: nextcloud
  password: ""          # ignored when mariadb.enabled=true
  existingSecret: ""    # e.g., nextcloud-db with keys: db-username, db-password

# --- Resources for the Nextcloud web pod (tune to taste) ---
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

# --- Optional cronjobs (preview generator etc.) ---
cronjob:
  enabled: false

metrics:
  enabled: false

# --- Annotations / labels (add what you need for ArgoCD, monitoring, etc.) ---
podAnnotations: {}
podLabels: {}

# --- Node scheduling (optional) ---
nodeSelector: {}
affinity: {}
tolerations: []
