apiVersion: v1
kind: Pod
metadata:
  name: cephfs-volume-test
spec:
  containers:
  - name: volume-test
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "CephFS EC storage test - $(date)" > /data/test.txt;
          echo "File contents:" && cat /data/test.txt;
          echo "File system type:" && df -Th /data;
          echo "Directory listing:" && ls -la /data;
          sleep 60;
        done
    volumeMounts:
    - name: cephfs-volume
      mountPath: /data
  volumes:
  - name: cephfs-volume
    persistentVolumeClaim:
      claimName: test-cephfs-ec-claim