apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-cephfs-ec-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block-storage-ec