# HTTP: catch and redirect to HTTPS (uses kube-system middleware)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-http
  namespace: n8n
spec:
  entryPoints: ["web"]
  routes:
    - match: Host(`n8n.local`)
      kind: Rule
      middlewares:
        - name: redirect-https
          namespace: kube-system
      services:
        - name: n8n
          port: 5678

---
# HTTPS: real route with TLS + headers middleware
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-https
  namespace: n8n
spec:
  entryPoints: ["websecure"]
  routes:
    - match: Host(`n8n.local`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: n8n
          port: 5678
  tls:
    secretName: n8n-local-tls   # secret lives in namespace n8n

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: n8n
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: n8n
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
    contentTypeNosniff: true
    browserXssFilter: true
    forceSTSHeader: true