apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-openwebui-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seadogger/seadogger-homelab.git
    targetRevision: HEAD
    path: kubectl-deployments/traefik
    directory:
      include: traefik-openwebui-service.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
