---
- name: "Graceful Cleanup (API-based)"
  hosts: control_plane
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Set KUBECONFIG global
      ansible.builtin.set_fact:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: "STAGE 1: Clean up all Applications and Services"
      ansible.builtin.include_tasks:
        file: tasks/cleanup_pod_item.yml
      loop: "{{ pod_cleanup_list }}"
      loop_control:
        loop_var: app
      when: run_pod_cleanup | default(false)

    - name: "STAGE 2: Clean up all Core Infrastructure"
      import_tasks: tasks/cleanup_infrastructure.yml
      when: run_infrastructure_cleanup | default(false)

- name: "Destructive Wipe (Node-based)"
  hosts: all
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: "STAGE 3: Wipe K3s Cluster (COLD START)"
      import_tasks: tasks/wipe_k3s_cluster.yml
      when: cold_start_stage_1_wipe_cluster | default(false)
