---
- hosts: cluster
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Wipe K3s Cluster
      import_tasks: tasks/wipe_k3s_cluster.yml
      when: enable_wipe_k3s_cluster | default(false)
- hosts: cluster
  gather_facts: true
  become: true
  handlers:
    - name: reboot-pi
      ansible.builtin.reboot:
  tasks:
    - name: Configure Raspberry Pi Cluster
      import_tasks: tasks/raspberry_pi_config.yml
      when: enable_raspberry_pi_config | default(true)

- hosts: control_plane
  gather_facts: false
  become: true
  handlers:
    - name: reboot-pi
      ansible.builtin.reboot:
  vars_files:
    - config.yml
  tasks:
    - name: Deploy and Configure k3s control plane
      import_tasks: tasks/k3s_control_plane.yml
      when: enable_k3s_control_plane | default(true)

- hosts: nodes
  gather_facts: false
  become: true
  handlers:
    - name: reboot-pi
      ansible.builtin.reboot:
  vars_files:
    - config.yml
  tasks:
    - name: Deploy and Configure k3s workers
      import_tasks: tasks/k3s_workers.yml
      when: enable_k3s_workers | default(true)

- hosts: control_plane
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Deploy Rook-Ceph - Part 1 (Core Components)
      import_tasks: tasks/rook_ceph_deploy_part1.yml
      when: enable_rook_ceph_part1 | default(false)

    - name: Deploy ArgoCD
      import_tasks: tasks/argocd_deploy.yml
      when: enable_argocd | default(true)

    - name: Deploy MetalLB
      import_tasks: tasks/metallb_deploy.yml
      when: enable_metallb | default(true)

    - name: Deploy ArgoCD SVC
      import_tasks: tasks/argocd_svc_metallb_deploy.yml
      when: enable_argocd_svc | default(true)

    - name: Deploy Rook-Ceph - Part 2 (NFS Server)
      import_tasks: tasks/rook_ceph_deploy_part2.yml
      when: enable_rook_ceph_part2 | default(false)

    - name: Deploy Bedrock Gateway
      import_tasks: tasks/bedrock_gateway_deploy.yml
      when: enable_bedrock | default(true)

    - name: Deploy PiHole
      import_tasks: tasks/pihole_deploy.yml
      when: enable_pihole | default(true)

    - name: Deploy Prometheus
      import_tasks: tasks/prometheus_deploy.yml
      when: enable_prometheus | default(true)

    - name: Deploy OpenWebUI
      import_tasks: tasks/openwebui_deploy.yml
      when: enable_openwebui | default(true)

    - name: Deploy PlexMediaServer
      import_tasks: tasks/plexmediaserver_deploy.yml
      when: enable_plex | default(true)

    - name: Deploy n8n
      import_tasks: tasks/n8n-deploy.yml
      when: enable_n8n | default(true)
