---
- hosts: cluster
  gather_facts: true
  become: true
  tasks:
    - name: Configure Raspberry Pi Cluster
      import_tasks: tasks/raspberry_pi_config.yml
      when: enable_raspberry_pi_config | default(true)

- hosts: control_plane
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Deploy and Configure k3s control plane
      import_tasks: tasks/k3s_control_plane.yml
      when: enable_k3s_control_plane | default(true)

- hosts: nodes
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Deploy and Configure k3s workers
      import_tasks: tasks/k3s_workers.yml
      when: enable_k3s_workers | default(true)

- hosts: control_plane
  gather_facts: false
  become: true
  vars_files:
    - config.yml
  tasks:
    - name: Deploy ArgoCD
      import_tasks: tasks/argocd_deploy.yml
      when: enable_argocd | default(true)

    - name: Deploy MetalLB
      import_tasks: tasks/metallb_deploy.yml
      when: enable_metallb | default(true)

    - name: Deploy ArgoCD SVC
      import_tasks: tasks/argocd_svc_metallb_deploy.yml
      when: enable_argocd_svc | default(true)

    - name: Deploy Bedrock Gateway
      import_tasks: tasks/bedrock_gateway_deploy.yml
      when: enable_bedrock | default(true)

    - name: Deploy PiHole
      import_tasks: tasks/pihole_deploy.yml
      when: enable_pihole | default(true)