apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "EC storage test - $(date)" > /data/test.txt;
          cat /data/test.txt;
          sleep 60;
        done
    volumeMounts:
    - name: ec-volume
      mountPath: /data
  volumes:
  - name: ec-volume
    persistentVolumeClaim:
      claimName: test-ec-claim