apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-ec-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-ec
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: test-volume-id