service:
  enabled: false  # Disable helm chart's service creation

main:
  persistence:
    enabled: true
    storageClass: "ceph-block-data"
    size: 50Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block-data"
      size: 50Gi
  auth:
    username: n8n
    password: n8npass
    database: n8n
