service:
  enabled: false  # Disable helm chart's service creation

persistence:
  enabled: true
  storageClass: "ceph-block"  # Using Ceph block storage
  size: 50Gi  # For n8n workflow data

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block"
      size: 50Gi
  auth:
    username: n8n
    password: n8npass
    database: n8n
