image:
  repository: docker.n8n.io/n8nio/n8n
  tag: 1.103.2
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  port: 5678

ingress:
  main:
    enabled: false

envVars:
  - name: GENERIC_TIMEZONE
    value: America/New_York
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: admin
  - name: N8N_BASIC_AUTH_PASSWORD
    value: changeme
  - name: WEBHOOK_URL
    value: "http://n8n.local"

persistence:
  data:
    enabled: true
    mountPath: /home/node/.n8n
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n
