service:
  enabled: false  # Disable helm chart's service creation

n8n:
  persistence:
    enabled: true
    storageClass: "ceph-block"
    size: 50Gi

# PostgreSQL configuration using Bitnami subchart
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block"
      size: 50Gi
  auth:
    username: n8n
    password: n8npass
    database: n8n
