service:
  enabled: false  # Disable helm chart's service creation

main:
  extraEnvVars:
    N8N_SECURE_COOKIE: false
      
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: false
  auth:
    username: n8n
    password: n8npass
    database: n8n