service:
  type: LoadBalancer
  port: 5678

main:
  extraEnvVars:
    - name: N8N_SECURE_COOKIE
      value: "false"

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: false
  auth:
    username: n8n
    password: n8npass
    database: n8n
