service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  # n8n served from /n8n (NO Traefik rewriting)
  extraEnvVars:
    N8N_PROTOCOL: "http"                       # in-cluster protocol
    N8N_PORT: "5678"                          # port for n8n to listen on
    N8N_PATH: "/n8n"                          # base path for n8n
    N8N_EDITOR_BASE_URL: "https://n8n.local/n8n"  # external URL with base path
    NODE_ENV: "production"                     # ensure production mode
    DB_SQLITE_POOL_SIZE: "10"                 # fix deprecation warning

ingress:
  enabled: false

# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n
