service:
  enabled: true
  type: LoadBalancer
  port: 5678
  loadBalancerIP: "192.168.1.252"
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: n8n

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  volumes:
    - name: n8n-ssl
      secret:
        secretName: n8n-local-tls
  volumeMounts:
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.crt
      subPath: tls.crt
      readOnly: true
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.key
      subPath: tls.key
      readOnly: true

  extraEnvVars:
    N8N_PROTOCOL: "https"
    N8N_PORT: "5678"
    N8N_SSL_CERT: "/etc/n8n/tls.crt"
    N8N_SSL_KEY: "/etc/n8n/tls.key"
    N8N_SECURE_COOKIE: "false"
    NODE_ENV: "production"
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    GENERIC_TIMEZONE: "America/New_York"
    N8N_DEFAULT_LOCALE: "en"
    N8N_HIRING_BANNER_ENABLED: "false"
    N8N_GRACEFUL_SHUTDOWN_TIMEOUT: "30"

  # disable probes to avoid any scheme/type mismatch
  livenessProbe: null
  readinessProbe: null

db:
  type: postgresdb

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block-data
      size: 50Gi
      accessMode: ReadWriteOnce
  auth:
    username: n8n
    password: n8npass
    database: n8n
