image:
  repository: docker.n8n.io/n8nio/n8n
  tag: 1.103.2
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: LoadBalancer
  port: 5678

ingress:
  enabled: false

env:
  GENERIC_TIMEZONE: America/New_York
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: admin
  N8N_BASIC_AUTH_PASSWORD: changeme
  WEBHOOK_URL: "http://n8n.local"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""

postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n
