service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  # n8n served from /n8n (NO Traefik rewriting)
  extraEnvVars:
    N8N_PATH: "/n8n/"                          # base path (note the trailing slash)
    N8N_PROTOCOL: "http"                       # in-cluster protocol
    N8N_PORT: "5678"
    # trust one reverse proxy (Traefik) for X-Forwarded-* headers
    N8N_PROXY_HOPS: "1"
    # public URLs so links & webhooks include /n8n
    N8N_EDITOR_BASE_URL: "https://seadogger-homelab.local/n8n"
    WEBHOOK_URL: "https://seadogger-homelab.local/n8n"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: seadogger-homelab.local
      paths:
        - path: /n8n
          pathType: Prefix
  tls:
    - secretName: n8n-local-tls
      hosts:
        - seadogger-homelab.local


# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n
