service:
  enabled: false  # you’re exposing n8n some other way (e.g., your own LB/Ingress)

main:
  replicaCount: 1

  # Persistent data for /home/node/.n8n
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi
    accessModes: [ "ReadWriteOnce" ]

  # Add container environment variables
  extraEnv:
    - name: N8N_PROTOCOL
      value: "https"
    - name: N8N_PORT
      value: "5678"
    - name: N8N_SSL_KEY
      value: "/etc/n8n/tls.key"
    - name: N8N_SSL_CERT
      value: "/etc/n8n/tls.crt"
    - name: N8N_SECURE_COOKIE
      value: "false"
    - name: N8N_HIRING_BANNER_ENABLED
      value: "false"
    - name: NODE_ENV
      value: "production"
    - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
      value: "true"
    - name: N8N_DEFAULT_LOCALE
      value: "en"
    - name: GENERIC_TIMEZONE
      value: "America/New_York"
    - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
      value: "30"

  # Mount your TLS secret created in the *same namespace as the release* (e.g., n8n)
  extraVolumes:
    - name: n8n-ssl
      secret:
        secretName: n8n-local-tls

  extraVolumeMounts:
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.crt
      subPath: tls.crt
      readOnly: true
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.key
      subPath: tls.key
      readOnly: true

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block-data
      size: 50Gi
      accessModes: [ "ReadWriteOnce" ]
  auth:
    username: n8n
    password: n8npass
    database: n8n
