service:
  enabled: true
  type: LoadBalancer
  port: 5678
  name: http
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: n8n
    metallb.universe.tf/loadBalancerIPs: "192.168.1.252"
  labels:
    app: n8n

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  volumes:
    - name: n8n-ssl
      secret:
        secretName: n8n-local-tls
  volumeMounts:
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.crt
      subPath: tls.crt
      readOnly: true
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.key
      subPath: tls.key
      readOnly: true

  extraEnvVars:
    N8N_SSL_CERT: "/etc/n8n/tls.crt"
    N8N_SSL_KEY: "/etc/n8n/tls.key"

timezone: "America/New_York"