service:
  enabled: false  # Disable helm chart's service creation

main:
  persistence:
    enabled: true
    storageClass: "ceph-block"
    size: 50Gi

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block"
      size: 50Gi
      volumeName: "data"
      mountPath: /bitnami/postgresql
  auth:
    username: n8n
    password: n8npass
    database: n8n
