image:
  repository: docker.n8n.io/n8nio/n8n
  tag: 1.103.2

service:
  enabled: true
  type: LoadBalancer
  port: 5678

ingress:
  enabled: false

env:
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: admin
  N8N_BASIC_AUTH_PASSWORD: changeme
  GENERIC_TIMEZONE: America/New_York
  WEBHOOK_URL: "http://n8n.local"

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n
