service:
  type: LoadBalancer
  port: 5678

deployment:
  env:
    - name: N8N_SECURE_COOKIE
      value: "false"

postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n

persistence:
  enabled: false
