service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http

main:
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  # n8n served from /n8n (NO Traefik rewriting)
  extraEnvVars:
    N8N_PATH: "/n8n/"                          # base path (note the trailing slash)
    N8N_PROTOCOL: "http"                       # in-cluster protocol
    N8N_PORT: "5678"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversTransport: ""
  hosts:
    - host: n8n.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-local-tls
      hosts:
        - n8n.local


# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n
