ingress:
  enabled: false

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.251
  port: 5678

n8n:
  basicAuth:
    enabled: true
    user: admin
    password: changeme
  timezone: America/New_York
  env:
    - name: N8N_HOST
      value: n8n.local
    - name: N8N_PORT
      value: "5678"
    - name: N8N_PROTOCOL
      value: http
  extraEnv:
    - name: GENERIC_TIMEZONE
      value: America/New_York
  webhookUrl: "http://n8n.local:5678"

postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n
