service:
  enabled: true
  type: LoadBalancer
  port: 5678
  name: http
  # Optional MetalLB pin:
  # loadBalancerIP: 192.168.1.252
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: "true"

main:
  persistence:
    enabled: true
    storageClass: "ceph-block-data"
    size: 50Gi

  extraEnvVars:
    N8N_PROTOCOL: "https"
    N8N_SECURE_COOKIE: "false"
    N8N_SSL_KEY: "/etc/n8n/tls.key"
    N8N_SSL_CERT: "/etc/n8n/tls.crt"
    N8N_HIRING_BANNER_ENABLED: "false"
    NODE_ENV: "production"
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
    N8N_PORT: "5678"
    N8N_DEFAULT_LOCALE: "en"
    GENERIC_TIMEZONE: "America/New_York"
    N8N_GRACEFUL_SHUTDOWN_TIMEOUT: "30"

  volumes:
    - name: n8n-ssl
      secret:
        secretName: n8n-local-tls
  volumeMounts:
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.crt
      subPath: tls.crt
      readOnly: true
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.key
      subPath: tls.key
      readOnly: true

  # Probes must use the named port "http" and SCHEME=HTTPS (UPPERCASE)
  livenessProbe:
    httpGet:
      path: /healthz
      port: "http"
      scheme: HTTPS
  readinessProbe:
    httpGet:
      path: /healthz/readiness
      port: "http"
      scheme: HTTPS

db:
  type: postgresdb

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClass: "ceph-block-data"
      size: 50Gi
      accessMode: ReadWriteOnce
  auth:
    username: n8n
    password: n8npass
    database: n8n
