# Disable the chart-created Service (you’ll expose n8n some other way, e.g., Ingress or an external SVC)
service:
  enabled: false

# Primary n8n workload configuration
main:
  replicaCount: 1

  # Persistent data for /home/node/.n8n
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi
    accessMode: ReadWriteOnce
    # mountPath defaults to /home/node/.n8n (chart default). You can set it explicitly if you like:
    # mountPath: /home/node/.n8n

  # Environment variables (use list-of-name/value pairs for this chart)
  env:
    - name: N8N_PROTOCOL
      value: "https"                    # only set this if you terminate TLS inside the pod
    - name: N8N_PORT
      value: "5678"
    - name: N8N_SECURE_COOKIE
      value: "false"
    - name: N8N_SSL_KEY
      value: "/etc/n8n/tls.key"
    - name: N8N_SSL_CERT
      value: "/etc/n8n/tls.crt"
    - name: NODE_ENV
      value: "production"
    - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
      value: "true"
    - name: N8N_DEFAULT_LOCALE
      value: "en"
    - name: GENERIC_TIMEZONE
      value: "America/New_York"
    - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
      value: "30"

  # Mount the TLS secret at /etc/n8n (this chart’s supported way to add secrets)
  secretVolumes:
    - name: n8n-ssl
      secretName: n8n-local-tls        # <-- must exist in the SAME namespace as the n8n release
      mountPath: /etc/n8n              # files become /etc/n8n/tls.crt and /etc/n8n/tls.key

# Bundle-provided PostgreSQL (Bitnami) with its own PVC
postgresql:
  enabled: true
  auth:
    username: n8n
    password: n8npass
    database: n8n
  primary:
    persistence:
      enabled: true
      storageClass: ceph-block-data
      size: 50Gi
      accessModes:
        - ReadWriteOnce
