main:
  replicaCount: 1
  extraEnvVars:
    - name: N8N_PROTOCOL
      value: "https"
    - name: N8N_SECURE_COOKIE
      value: "false"
    - name: N8N_SSL_KEY
      value: "/etc/n8n/tls.key"
    - name: N8N_SSL_CERT
      value: "/etc/n8n/tls.crt"
    - name: N8N_HIRING_BANNER_ENABLED
      value: "false"
    - name: NODE_ENV
      value: "production"
    - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
      value: "true"
    - name: N8N_PORT
      value: "5678"
    - name: N8N_DEFAULT_LOCALE
      value: "en"
    - name: GENERIC_TIMEZONE
      value: "America/New_York"
    - name: N8N_GRACEFUL_SHUTDOWN_TIMEOUT
      value: "30"

  persistence:
    enabled: true
    storageClassName: "ceph-block-data"
    size: 50Gi
    accessMode: ReadWriteOnce

  extraVolumes:
    - name: n8n-ssl
      secret:
        secretName: n8n-local-tls

  extraVolumeMounts:
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.crt
      subPath: tls.crt
    - name: n8n-ssl
      mountPath: /etc/n8n/tls.key
      subPath: tls.key

service:
  type: LoadBalancer
  loadBalancerIP: "192.168.1.252"
  ports:
    - name: http
      port: 80
      targetPort: 5678
    - name: https
      port: 443
      targetPort: 5678

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      storageClassName: "ceph-block-data"
      size: 50Gi
      accessMode: ReadWriteOnce
  auth:
    username: n8n
    password: n8npass
    database: n8n
