service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: "192.168.1.252"
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.1.252"
  labels:
    app.kubernetes.io/name: n8n
    app.kubernetes.io/instance: n8n

main:
  extraEnvVars:
    - name: N8N_SECURE_COOKIE
      value: "false"
    - name: N8N_HOST
      value: "192.168.1.252"
    - name: N8N_PROTOCOL
      value: "http"
    - name: N8N_PORT
      value: "80"
      
postgresql:
  enabled: true
  primary:
    persistence:
      enabled: false
  auth:
    username: n8n
    password: n8npass
    database: n8n