# --- Service stays internal; Traefik will front it via Ingress
service:
  enabled: true
  type: ClusterIP
  port: 5678
  name: http
  annotations: {}
  labels: {}

main:
  # Persist ~/.n8n on your Ceph SC
  persistence:
    enabled: true
    storageClass: ceph-block-data
    size: 50Gi

  # n8n listens in HTTP; Traefik does TLS
  extraEnvVars:
    N8N_PROTOCOL: "http"
    N8N_PORT: "5678"

timezone: "America/New_York"

# --- Traefik Ingress (TLS terminated by Traefik using your cert-manager secret)
ingress:
  enabled: true
  className: "traefik"   # k3s default IngressClass
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: n8n.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-local-tls   # cert-manager Secret in the n8n namespace
      hosts:
        - n8n.local

# --- OPTIONAL: Built-in PostgreSQL (uncomment if you want chart-managed DB)
# db:
#   type: postgresdb
#
# postgresql:
#   enabled: true
#   primary:
#     persistence:
#       enabled: true
#       storageClass: ceph-block-data
#       size: 50Gi
#   auth:
#     username: n8n
#     password: n8npass
#     database: n8n
