apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: yoda
  namespace: longhorn-system
spec:
  allowScheduling: true
  tags: ["storage"]
  disks:
    default-disk-ebc9eabe234c75a:
      allowScheduling: false
      path: /var/lib/longhorn/
      storageReserved: 14656403865
      tags: []
    ssd-disk:
      allowScheduling: true
      path: /mnt/longhorn
      storageReserved: 0
      tags: ["ssd"]
      diskType: filesystem
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: obiwan
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks:
    default-disk-974282496afae629:
      allowScheduling: false
      path: /var/lib/longhorn/
      storageReserved: 18751469568
      tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: vader
  namespace: longhorn-system
spec:
  allowScheduling: false
  disks:
    default-disk-974282496afae629:
      allowScheduling: false
      path: /var/lib/longhorn/
      storageReserved: 4436905574
      tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-data-path
  namespace: longhorn-system
value: "/var/lib/longhorn/"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: create-default-disk-labeled-nodes
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-minimal-available-percentage
  namespace: longhorn-system
value: "10"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-over-provisioning-percentage
  namespace: longhorn-system
value: "100"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: upgrade-checker
  namespace: longhorn-system
value: "false"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: concurrent-automatic-engine-upgrade-per-node-limit
  namespace: longhorn-system
value: "1"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: kubernetes-cluster-autoscaler-enabled
  namespace: longhorn-system
value: "false"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: storage-reserved-percentage-for-default-disk
  namespace: longhorn-system
value: "25"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: auto-cleanup-system-generated-snapshot
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: concurrent-replica-rebuild-per-node-limit
  namespace: longhorn-system
value: "2"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: system-managed-pods-image-pull-policy
  namespace: longhorn-system
value: "if-not-present"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: allow-recurring-job-while-volume-detached
  namespace: longhorn-system
value: "false"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: fast-replica-rebuild-enabled
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: replica-zone-soft-anti-affinity
  namespace: longhorn-system
value: "true"
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: default-replica-count
  namespace: longhorn-system
spec:
  value: "2"