apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-config
  namespace: rook-ceph
data:
  ceph.conf: |
    [global]
    mon_host = 192.168.1.98:6789
    auth_cluster_required = cephx
    auth_service_required = cephx
    auth_client_required = cephx