apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.0
    allowUnsupported: true
    imagePullPolicy: Always
    imagePullSpec:
      platform:
        architecture: arm64
        os: linux
  dashboard:
    enabled: true
    ssl: false
  network:
    provider: host
  crashCollector:
    disable: true
  monitoring:
    enabled: false
  storage:
    useAllNodes: false
    useAllDevices: false
    nodes:
      - name: "obiwan"
        devices:
          - name: "nvme0n1p3"
      - name: "anakin"
        devices:
          - name: "nvme0n1p3"
      - name: "rey"
        devices:
          - name: "nvme0n1p3"
  placement:
    all:
      tolerations:
        - operator: "Exists"