apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /var/lib/rook
  mon:
    count: 1
    allowMultiplePerNode: true
  cephVersion:
    image: quay.io/ceph/ceph:v17.2.6
    allowUnsupported: true
  dashboard:
    enabled: true
  storage:
    useAllNodes: false
    useAllDevices: false
    config:
      osdsPerDevice: "1"
      encryptedDevice: "false"
      allowPartitons: "true"  # This is important when using partitions
    nodes:
      - name: "obiwan"  # Replace with your first worker node name
        devices:
          - name: "nvme0n1p3"  # Replace with your actual NVMe device name
      - name: "anakin"  # Replace with your second worker node name
        devices:
          - name: "nvme0n1p3"  # Replace with your actual NVMe device name
      # Add more worker nodes as needed
  resources:
    mgr:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    mon:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
    osd:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist