apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ec-data
  namespace: rook-ceph
spec:
  failureDomain: host
  erasureCoded:
    dataChunks: 2   # Number of data chunks
    codingChunks: 1 # Number of coding chunks