apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-cephfs-pvc
  namespace: rook-ceph
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-ceph-filesystem
  resources:
    requests:
      storage: 500Gi