apiVersion: batch/v1
kind: Job
metadata:
  name: rook-ceph-osd-prepare-rey
  namespace: rook-ceph
  labels:
    app: rook-ceph-osd-prepare
spec:
  template:
    spec:
      containers:
      - name: osd-prepare
        image: quay.io/ceph/ceph:v19.2.0
        command: ["/usr/bin/ceph-volume"]
        args: ["--log-path", "/tmp/ceph-log", "lvm", "batch", "--prepare", "/dev/nvme0n1p3", "--yes"]
        env:
        - name: ROOK_NODE_NAME
          value: rey
        securityContext:
          privileged: true
        volumeMounts:
        - name: devices
          mountPath: /dev
        - name: discover
          mountPath: /dev/disk
        - name: rook-data
          mountPath: /var/lib/rook
      volumes:
      - name: devices
        hostPath:
          path: /dev
      - name: discover
        hostPath:
          path: /dev/disk
      - name: rook-data
        hostPath:
          path: /var/lib/rook
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: rey
      tolerations:
      - operator: Exists