# Replicated metadata pool
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ecpool-metadata
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 3
  parameters:
    compression_mode: aggressive
  statusCheck:
    mirror: {}
---
# Erasure-coded data pool
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: ecpool
  namespace: rook-ceph
spec:
  failureDomain: host
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
  parameters:
    compression_mode: aggressive
  statusCheck:
    mirror: {}