apiVersion: ceph.rook.io/v1
kind: CephRBDMirror
metadata:
  name: rbd-mirror
  namespace: rook-ceph
spec:
  count: 1
  placement:
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
    topologySpreadConstraints: []
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"