csi:
  kubeletDirPath: /var/lib/kubelet
  enableCSIHostNetwork: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

discover:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Adjust tolerations if you have arm64 architecture
nodeSelector:
  kubernetes.io/arch: arm64