apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: myblockpool-ec-data
  namespace: rook-ceph
spec:
  failureDomain: host
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
  parameters:
    compression_mode: aggressive
    allow_ec_overwrites: "true"
  statusCheck:
    mirror: {}