apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph
type: Opaque
data:
  key: "AQCrnrpnchmxChAA+xsYr1HmDdYpRYJcOFD/Kg=="
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph
type: Opaque
data:
  key: "AQCrnrpnchmxChAA+xsYr1HmDdYpRYJcOFD/Kg=="
