apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          echo "Block storage test" > /block/test.txt;
          echo "Filesystem storage test" > /shared/test.txt;
          sleep 3600;
        done
    volumeMounts:
    - name: block-volume
      mountPath: /block
    - name: shared-volume
      mountPath: /shared
  volumes:
  - name: block-volume
    persistentVolumeClaim:
      claimName: test-block-claim
  - name: shared-volume
    persistentVolumeClaim:
      claimName: test-fs-claim