apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-ceph-tools
  namespace: rook-ceph
  labels:
    app: rook-ceph-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-ceph-tools
  template:
    metadata:
      labels:
        app: rook-ceph-tools
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rook-ceph-tools
        image: rook/ceph:v1.12.3
        command: ["/bin/bash"]
        args:
          - -c
          - |
            CEPH_CONF=/etc/ceph/ceph.conf
            MON_IP=$(cat /etc/rook/mon-endpoints | cut -d'=' -f2)
            KEYRING=/etc/ceph/keyring

            cat << EOF > $CEPH_CONF
            [global]
            mon_host = ${MON_IP}
            auth_cluster_required = cephx
            auth_service_required = cephx
            auth_client_required = cephx
            EOF

            # Create keyring file
            cat << EOF > $KEYRING
            [client.admin]
                key = $(cat /etc/ceph-secret/secret)
                caps mds = "allow *"
                caps mon = "allow *"
                caps osd = "allow *"
                caps mgr = "allow *"
            EOF

            chmod 600 $KEYRING
            
            # Keep the container running
            while true; do 
              sleep 3600
            done
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          privileged: true
        volumeMounts:
          - mountPath: /etc/ceph
            name: ceph-config
          - name: mon-endpoint-volume
            mountPath: /etc/rook
          - name: ceph-admin-secret
            mountPath: /etc/ceph-secret
            readOnly: true
      serviceAccountName: rook-ceph-tools
      volumes:
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
            - key: data
              path: mon-endpoints
        - name: ceph-config
          emptyDir: {}
        - name: ceph-admin-secret
          secret:
            secretName: rook-ceph-mon
            items:
              - key: ceph-secret
                path: secret